# Generated by Django 5.2 on 2025-04-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusercurrentemotion',
            name='feeling',
            field=models.CharField(help_text='How the user is feeling right now', max_length=255),
        ),
        migrations.AlterField(
            model_name='appuserdailyemotion',
            name='feeling',
            field=models.CharField(help_text='How the user felt overall today', max_length=255),
        ),
    ]
