# Generated by Django 5.2 on 2025-05-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appusercurrentemotion_feeling_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appuserdailyemotion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='appuserdailyemotion',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppUserCurrentEmotion',
        ),
        migrations.DeleteModel(
            name='AppUserDailyEmotion',
        ),
    ]
