# Generated by Django 5.2 on 2025-05-03 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appuserdailyemotion_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserCurrentEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='neutral', max_length=20)),
                ('intensity', models.IntegerField(default=5)),
                ('cause', models.TextField(default='')),
                ('biggest_impact', models.TextField(default='')),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_emotions', to='api.appuser')),
            ],
            options={
                'ordering': ['-tracked_at'],
            },
        ),
        migrations.CreateModel(
            name='AppUserDailyEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(default='neutral', max_length=20)),
                ('intensity', models.IntegerField(default=5)),
                ('cause', models.TextField(default='')),
                ('biggest_impact', models.TextField(default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_emotions', to='api.appuser')),
            ],
            options={
                'ordering': ['-tracked_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
