# Generated by Django 5.1.6 on 2025-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appusercurrentemotion_appuserdailyemotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='available_points',
            field=models.IntegerField(default=0, help_text='Points currently available for the user to spend.'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lifetime_points',
            field=models.IntegerField(default=0, help_text='Total points earned by the user over their lifetime.'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lifetime_savings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total savings earned by the user over their lifetime in dollars.', max_digits=10),
        ),
    ]
