# Generated by Django 5.1.6 on 2025-04-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_appuser_available_points_appuser_lifetime_points_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberList',
        ),
        migrations.AddField(
            model_name='affiliatepromotion',
            name='product_image',
            field=models.URLField(blank=True, help_text='URL of an image representing the product or promotion.', null=True),
        ),
    ]
