# Generated by Django 5.1.6 on 2025-04-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_delete_phonenumberlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email for the affiliate.', max_length=254, null=True, unique=True),
        ),
    ]
