# Generated by Django 5.1.6 on 2025-04-30 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_affiliate_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendcircleevent',
            name='user',
            field=models.ForeignKey(help_text='The user associated with the event (joined, left, completed activity).', on_delete=django.db.models.deletion.CASCADE, related_name='friend_circle_events', to='api.appuser'),
        ),
    ]
