# Generated by Django 5.1.6 on 2025-04-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_friendcircleevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingcontent',
            name='content_cards',
        ),
        migrations.AddField(
            model_name='contentcard',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the card within the reading content.'),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='reading_content',
            field=models.ForeignKey(help_text='The ReadingContent this card belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_cards', to='api.readingcontent'),
        ),
    ]
