# Generated by Django 5.1.6 on 2025-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_readingcontent_content_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcard',
            name='bolded_words',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of words that should be bolded in the text. These words must exist in the text.', null=True),
        ),
    ]
