# Generated by Django 5.1.6 on 2025-04-30 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_contentcard_bolded_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number in 1234567890 format.', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890'. Exactly 10 digits allowed.", regex='^\\d{10}$')]),
        ),
    ]
