# Generated by Django 5.1.6 on 2025-04-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_affiliate_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepromotion',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Image of the product being offered.', null=True, upload_to='affiliate_product_images/'),
        ),
    ]
