# Generated by Django 5.1.6 on 2025-04-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_affiliatepromotion_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatepromotion',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price of the product/service before the promotion, in dollars.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='affiliatepromotion',
            name='point_value',
            field=models.IntegerField(default=0, help_text='Amount of points this promotions costs.'),
        ),
    ]
