# Generated by Django 5.1.6 on 2025-05-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_affiliatepromotion_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo of the affiliate.', null=True, upload_to='affiliate_logos/'),
        ),
    ]
