# Generated by Django 5.1.6 on 2025-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_affiliate_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the affiliate.', max_length=255, null=True),
        ),
    ]
