# Generated by Django 5.1.6 on 2025-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_affiliate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='isOnboarded',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has completed the onboarding process.'),
        ),
    ]
