# Generated by Django 5.1.6 on 2025-05-02 00:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_appuser_isonboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusergoals',
            name='goals_processed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('improve_endurance', 'Improve Endurance'), ('increase_flexibility', 'Increase Flexibility')], max_length=50), blank=True, default=list, help_text='A list of processed goals, restricted to allowed choices. Can be blank.', size=None),
        ),
    ]
