# Generated by Django 5.1.6 on 2025-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_appusergoals_goals_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcircle',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the friend circle.', null=True, upload_to='friend_circle_covers/'),
        ),
    ]
