# Generated by Django 5.1.6 on 2025-05-05 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_friendcircle_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusercompletedactivity',
            options={'ordering': ['-completed_at'], 'verbose_name': 'User Completed Activity Record', 'verbose_name_plural': 'User Completed Activity Records'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='isComplete',
        ),
        migrations.RemoveField(
            model_name='appusercurrentactivityplan',
            name='dateCompleted',
        ),
        migrations.RemoveField(
            model_name='appusercurrentactivityplan',
            name='isComplete',
        ),
        migrations.AlterField(
            model_name='appusercompletedactivity',
            name='activity',
            field=models.ForeignKey(help_text='The specific activity that was completed.', on_delete=django.db.models.deletion.CASCADE, related_name='completions_history', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='appusercompletedactivity',
            name='source_plan',
            field=models.ForeignKey(blank=True, help_text='The activity plan template this completion originated from, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activities_originating_from_plan', to='api.activityplan'),
        ),
        migrations.CreateModel(
            name='AppUserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True, help_text='The date this activity instance is scheduled for completion.')),
                ('is_complete', models.BooleanField(db_index=True, default=False, help_text='Indicates if this specific activity instance has been completed by the user.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when this specific activity instance was marked as completed.', null=True)),
                ('activity', models.ForeignKey(help_text='The specific activity for this instance.', on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='api.activity')),
                ('current_plan_assignment', models.ForeignKey(help_text='The specific plan assignment this activity instance belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_instances_in_plan', to='api.appusercurrentactivityplan')),
                ('user', models.ForeignKey(help_text='The user for whom this activity instance is intended.', on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='api.appuser')),
            ],
            options={
                'verbose_name': 'User Activity Instance',
                'verbose_name_plural': 'User Activity Instances',
                'ordering': ['scheduled_date', 'user'],
                'unique_together': {('current_plan_assignment', 'activity', 'scheduled_date')},
            },
        ),
        migrations.AddField(
            model_name='appusercompletedactivity',
            name='user_activity_instance',
            field=models.ForeignKey(blank=True, help_text='Link to the specific user activity instance, if completed as part of a plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_record', to='api.appuseractivity'),
        ),
    ]
