# Generated by Django 5.1.6 on 2025-05-06 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_appusercompletedactivity_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='pointValue',
            new_name='default_point_value',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to hide this activity template from new selections.'),
        ),
        migrations.CreateModel(
            name='UserScheduledActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(db_index=True, help_text='The date this activity is scheduled for completion.')),
                ('is_generated', models.BooleanField(default=False, help_text='True if generated by the system (e.g., weekly AI), False if manually added by the user.')),
                ('order_in_day', models.PositiveIntegerField(default=0, help_text='Order of the activity within the scheduled day if multiple activities.')),
                ('is_complete', models.BooleanField(db_index=True, default=False, help_text='Indicates if this specific scheduled activity has been completed by the user.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when this scheduled activity was marked as completed.', null=True)),
                ('custom_notes', models.TextField(blank=True, help_text="User's notes specifically for this scheduled instance (e.g., 'Ran 5km instead of 3km').", null=True)),
                ('activity', models.ForeignKey(help_text='The specific activity template scheduled.', on_delete=django.db.models.deletion.PROTECT, to='api.activity')),
                ('user', models.ForeignKey(help_text='The user for whom this activity is scheduled.', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_activities', to='api.appuser')),
            ],
            options={
                'verbose_name': 'User Scheduled Activity',
                'verbose_name_plural': 'User Scheduled Activities',
                'ordering': ['user', 'scheduled_date', 'order_in_day'],
                'unique_together': {('user', 'activity', 'scheduled_date', 'order_in_day')},
            },
        ),
        migrations.CreateModel(
            name='UserCompletedLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name_at_completion', models.CharField(help_text='Denormalized name of the activity as it was when completed.', max_length=255)),
                ('description_at_completion', models.TextField(blank=True, help_text='Denormalized description of the activity as it was when completed.')),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the activity was marked as completed by the user.')),
                ('points_awarded', models.IntegerField(help_text='Points actually awarded for this specific completion.')),
                ('is_adhoc', models.BooleanField(default=False, help_text='True if this was an activity completed outside of a pre-defined schedule.')),
                ('user_notes_on_completion', models.TextField(blank=True, help_text='General notes from the user about this specific completion instance.', null=True)),
                ('activity', models.ForeignKey(blank=True, help_text='Link to the original activity template, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.activity')),
                ('user', models.ForeignKey(help_text='The user who completed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='api.appuser')),
                ('source_scheduled_activity', models.ForeignKey(blank=True, help_text='Link to the UserScheduledActivity instance if this completion corresponds to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_log_entries', to='api.userscheduledactivity')),
            ],
            options={
                'verbose_name': 'User Completion Log',
                'verbose_name_plural': 'User Completion Logs',
                'ordering': ['-completed_at'],
            },
        ),
    ]
