# Generated by Django 5.1.6 on 2025-05-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_rename_pointvalue_activity_default_point_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusercurrentactivityplan',
            name='activity_plan',
        ),
        migrations.RemoveField(
            model_name='appusercompletedactivity',
            name='source_plan',
        ),
        migrations.AlterUniqueTogether(
            name='appuseractivity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='appuseractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='appuseractivity',
            name='current_plan_assignment',
        ),
        migrations.RemoveField(
            model_name='appuseractivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appusercompletedactivity',
            name='user_activity_instance',
        ),
        migrations.RemoveField(
            model_name='appusercompletedactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='appusercompletedactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friendcircleevent',
            name='completed_activity',
        ),
        migrations.RemoveField(
            model_name='appusercurrentactivityplan',
            name='user',
        ),
        migrations.AddField(
            model_name='friendcircleevent',
            name='completed_activity_log',
            field=models.ForeignKey(blank=True, help_text='Link to the UserCompletedLog record, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_circle_event_links', to='api.usercompletedlog'),
        ),
        migrations.DeleteModel(
            name='ActivityPlan',
        ),
        migrations.DeleteModel(
            name='AppUserActivity',
        ),
        migrations.DeleteModel(
            name='AppUserCompletedActivity',
        ),
        migrations.DeleteModel(
            name='AppUserCurrentActivityPlan',
        ),
    ]
