# Generated by Django 5.1.6 on 2025-05-14 05:03

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_appuser_groups_appuser_is_active_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Sleep', 'Sleep'), ('Mind', 'Mind')], max_length=50), blank=True, default=list, help_text='Category or categories of the activity.', size=None),
        ),
        migrations.AlterField(
            model_name='appusergoals',
            name='goals_processed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('improve_endurance', 'Improve Endurance'), ('increase_flexibility', 'Increase Flexibility')], max_length=50), blank=True, default=list, help_text='A list of processed goals, restricted to allowed choices.', size=None),
        ),
        migrations.AlterField(
            model_name='contentcard',
            name='bolded_words',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of words that should be bolded in the text.', null=True),
        ),
        migrations.AlterField(
            model_name='friendcircleevent',
            name='user',
            field=models.ForeignKey(help_text='The user associated with the event.', on_delete=django.db.models.deletion.CASCADE, related_name='friend_circle_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='readingcontent',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Sleep', 'Sleep'), ('Mind', 'Mind')], max_length=50), blank=True, default=list, help_text='Category or categories of the reading content.', size=None),
        ),
        migrations.AlterField(
            model_name='usercompletedlog',
            name='completed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the activity was marked as completed.'),
        ),
        migrations.AlterField(
            model_name='userscheduledactivity',
            name='custom_notes',
            field=models.TextField(blank=True, help_text="User's notes specifically for this scheduled instance.", null=True),
        ),
        migrations.AlterField(
            model_name='userscheduledactivity',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if this specific scheduled activity has been completed.'),
        ),
        migrations.AlterField(
            model_name='userscheduledactivity',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='True if generated by the system, False if manually added by the user.'),
        ),
    ]
