# Generated by Django 5.1.6 on 2025-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_activity_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='lifetime_savings',
            field=models.IntegerField(default=0, help_text='Total savings earned by the user over their lifetime (e.g., in cents or smallest currency unit if not whole dollars).'),
        ),
    ]
