# Generated by Django 5.2.1 on 2025-05-15 19:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_appuser_lifetime_savings'),
        ('fitness', '0004_workoutexercise_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseMax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('one_rep_max', models.FloatField(help_text='The current 1-rep maximum weight (e.g., in lbs or kg).')),
                ('date_recorded', models.DateField(default=django.utils.timezone.now, help_text='The date when the current 1RM was achieved or recorded.')),
                ('previous_maxes', models.JSONField(blank=True, default=list, help_text="A list of previous 1-rep maximums, e.g., [{'value': 100, 'date': 'YYYY-MM-DD'}, ...]", null=True)),
                ('unit', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms')], default='lbs', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(help_text='The exercise for which this 1RM is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='user_maxes', to='fitness.exercise')),
                ('user', models.ForeignKey(help_text='The user for whom this 1RM is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_maxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Exercise Max',
                'verbose_name_plural': 'User Exercise Maxes',
                'ordering': ['user', '-date_recorded', 'exercise'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
