# Generated by Django 5.2.1 on 2025-05-15 20:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_userexercisemax'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserFatigueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, help_text='When this fatigue measurement was recorded.')),
                ('quadriceps', models.FloatField(default=0.0, help_text='Fatigue level for quadriceps (0-1)')),
                ('abdominals', models.FloatField(default=0.0, help_text='Fatigue level for abdominals (0-1)')),
                ('abductors', models.FloatField(default=0.0, help_text='Fatigue level for abductors (0-1)')),
                ('adductors', models.FloatField(default=0.0, help_text='Fatigue level for adductors (0-1)')),
                ('biceps', models.FloatField(default=0.0, help_text='Fatigue level for biceps (0-1)')),
                ('calves', models.FloatField(default=0.0, help_text='Fatigue level for calves (0-1)')),
                ('cardiovascular', models.FloatField(default=0.0, help_text='Fatigue level for cardiovascular system (0-1)')),
                ('chest', models.FloatField(default=0.0, help_text='Fatigue level for chest (0-1)')),
                ('forearms', models.FloatField(default=0.0, help_text='Fatigue level for forearms (0-1)')),
                ('full_body', models.FloatField(default=0.0, help_text='Overall full body fatigue level (0-1)')),
                ('glutes', models.FloatField(default=0.0, help_text='Fatigue level for glutes (0-1)')),
                ('hamstrings', models.FloatField(default=0.0, help_text='Fatigue level for hamstrings (0-1)')),
                ('lats', models.FloatField(default=0.0, help_text='Fatigue level for lats (0-1)')),
                ('lower_back', models.FloatField(default=0.0, help_text='Fatigue level for lower back (0-1)')),
                ('middle_back', models.FloatField(default=0.0, help_text='Fatigue level for middle back (0-1)')),
                ('neck', models.FloatField(default=0.0, help_text='Fatigue level for neck (0-1)')),
                ('shoulders', models.FloatField(default=0.0, help_text='Fatigue level for shoulders (0-1)')),
                ('traps', models.FloatField(default=0.0, help_text='Fatigue level for traps (0-1)')),
                ('triceps', models.FloatField(default=0.0, help_text='Fatigue level for triceps (0-1)')),
                ('user', models.ForeignKey(help_text='The user whose muscle fatigue is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='muscle_fatigue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Muscle Fatigue',
                'verbose_name_plural': 'User Muscle Fatigue Records',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
