# Generated by Django 5.2.1 on 2025-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_appuserfatiguemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='backup_email',
            field=models.EmailField(blank=True, help_text='Optional backup email address for the user.', max_length=255, null=True),
        ),
    ]
