# Generated by Django 5.2.1 on 2025-06-04 20:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_appuser_backup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusergoals',
            name='goals_processed',
        ),
        migrations.RemoveField(
            model_name='appusergoals',
            name='goals_raw',
        ),
        migrations.AddField(
            model_name='appusergoals',
            name='goals_general',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lose_weight', 'Lose weight'), ('build_muscle', 'Build muscle'), ('get_more_flexible', 'Get more flexible'), ('get_stronger', 'Get stronger'), ('eat_healthier', 'Eat healthier'), ('regulate_energy', 'Regulate energy'), ('sleep_better', 'Sleep better'), ('manage_stress', 'Manage stress'), ('drink_more_water', 'Drink more water')], max_length=50), blank=True, default=list, help_text='A list of general wellness goals selected by the user.', size=None),
        ),
        migrations.CreateModel(
            name='UserGoalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_category', models.CharField(choices=[('lose_weight', 'Lose weight'), ('build_muscle', 'Build muscle'), ('get_more_flexible', 'Get more flexible'), ('get_stronger', 'Get stronger'), ('eat_healthier', 'Eat healthier'), ('regulate_energy', 'Regulate energy'), ('sleep_better', 'Sleep better'), ('manage_stress', 'Manage stress'), ('drink_more_water', 'Drink more water')], help_text='The general goal category this detail pertains to.', max_length=50)),
                ('text', models.TextField(help_text='The specific detail or plan for the associated goal category.')),
                ('app_user_goals', models.ForeignKey(help_text='The set of user goals this detail belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.appusergoals')),
            ],
            options={
                'verbose_name': 'User Goal Detail',
                'verbose_name_plural': 'User Goal Details',
                'ordering': ['app_user_goals', 'goal_category'],
            },
        ),
    ]
