# Generated by Django 5.2.1 on 2025-06-05 21:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_appusergoals_goals_processed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergoaldetail',
            options={'ordering': ['app_user_goals'], 'verbose_name': 'User Goal Detail', 'verbose_name_plural': 'User Goal Details'},
        ),
        migrations.RemoveField(
            model_name='usergoaldetail',
            name='goal_category',
        ),
        migrations.AddField(
            model_name='usergoaldetail',
            name='goal_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lose_weight', 'Lose weight'), ('build_muscle', 'Build muscle'), ('get_more_flexible', 'Get more flexible'), ('get_stronger', 'Get stronger'), ('eat_healthier', 'Eat healthier'), ('regulate_energy', 'Regulate energy'), ('sleep_better', 'Sleep better'), ('manage_stress', 'Manage stress'), ('drink_more_water', 'Drink more water')], max_length=50), blank=True, db_column='goal_category', default=list, help_text='The general goal categories this detail pertains to (can be multiple).', size=None),
        ),
    ]
