# Generated by Django 5.2.1 on 2025-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_usergoaldetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserinfo',
            name='birthday',
            field=models.DateField(blank=True, help_text='Birthday of the user.', null=True),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in inches.', null=True),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Sex of the user.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in pounds.', null=True),
        ),
    ]
