# Generated by Django 5.2.1 on 2025-06-11 19:49

from django.db import migrations, models
import uuid

def gen_user_uuids(apps, schema_editor):
    AppUser = apps.get_model('api', 'AppUser')
    for user in AppUser.objects.all():
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid'])

def link_related_objects(apps, schema_editor):
    AppUser = apps.get_model('api', 'AppUser')

    related_models = [
        'AppUserInfo', 'AppUserGoals', 'UserScheduledActivity', 'UserCompletedLog',
        'AffiliatePromotionDiscountCode', 'AffiliatePromotionRedemption', 'Member',
        'FriendCircleEvent', 'AppUserCurrentEmotion', 'AppUserDailyEmotion',
        'UserExerciseMax', 'AppUserFatigueModel'
    ]

    for model_name in related_models:
        RelatedModel = apps.get_model('api', model_name)
        fk_field_name = ''
        if hasattr(RelatedModel._meta, 'one_to_one_field') and RelatedModel._meta.one_to_one_field and RelatedModel._meta.one_to_one_field.related_model == AppUser:
            fk_field_name = RelatedModel._meta.one_to_one_field.name
        else:
            for field in RelatedModel._meta.fields:
                if isinstance(field, (models.ForeignKey, models.OneToOneField)) and field.related_model == AppUser:
                    fk_field_name = field.name
                    break
        
        if not fk_field_name:
            if model_name == 'AffiliatePromotionDiscountCode':
                fk_field_name = 'assigned_user'
            else:
                continue

        new_fk_name = f"{fk_field_name}_uuid"
        
        for obj in RelatedModel.objects.all():
            user = getattr(obj, fk_field_name)
            if user:
                setattr(obj, new_fk_name, user.uuid)
                obj.save(update_fields=[new_fk_name])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_appuserinfo_birthday_alter_appuserinfo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(gen_user_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='appuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AddField(model_name='appuserinfo', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='appusergoals', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='userscheduledactivity', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='usercompletedlog', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='affiliatepromotiondiscountcode', name='assigned_user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='affiliatepromotionredemption', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='member', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='friendcircleevent', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='appusercurrentemotion', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='appuserdailyemotion', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='userexercisemax', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.AddField(model_name='appuserfatiguemodel', name='user_uuid', field=models.UUIDField(null=True)),
        migrations.RunPython(link_related_objects, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            """
            ALTER TABLE api_appuser_max_propositions ADD COLUMN appuser_uuid UUID;
            UPDATE api_appuser_max_propositions SET appuser_uuid = (SELECT uuid FROM api_appuser WHERE id = api_appuser_max_propositions.appuser_id);
            ALTER TABLE api_affiliatepromotion_assigned_users ADD COLUMN appuser_uuid UUID;
            UPDATE api_affiliatepromotion_assigned_users SET appuser_uuid = (SELECT uuid FROM api_appuser WHERE id = api_affiliatepromotion_assigned_users.appuser_id);
            ALTER TABLE auth_user_groups ADD COLUMN user_uuid UUID;
            UPDATE auth_user_groups SET user_uuid = (SELECT uuid FROM api_appuser WHERE id = auth_user_groups.user_id);
            ALTER TABLE auth_user_user_permissions ADD COLUMN user_uuid UUID;
            UPDATE auth_user_user_permissions SET user_uuid = (SELECT uuid FROM api_appuser WHERE id = auth_user_user_permissions.user_id);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RemoveField(model_name='appuserinfo', name='user'),
        migrations.RemoveField(model_name='appusergoals', name='user'),
        migrations.RemoveField(model_name='userscheduledactivity', name='user'),
        migrations.RemoveField(model_name='usercompletedlog', name='user'),
        migrations.RemoveField(model_name='affiliatepromotiondiscountcode', name='assigned_user'),
        migrations.RemoveField(model_name='affiliatepromotionredemption', name='user'),
        migrations.RemoveField(model_name='member', name='user'),
        migrations.RemoveField(model_name='friendcircleevent', name='user'),
        migrations.RemoveField(model_name='appusercurrentemotion', name='user'),
        migrations.RemoveField(model_name='appuserdailyemotion', name='user'),
        migrations.RemoveField(model_name='userexercisemax', name='user'),
        migrations.RemoveField(model_name='appuserfatiguemodel', name='user'),
        migrations.RunSQL(
            """
            ALTER TABLE api_appuser_max_propositions DROP COLUMN appuser_id;
            ALTER TABLE api_affiliatepromotion_assigned_users DROP COLUMN appuser_id;
            ALTER TABLE auth_user_groups DROP COLUMN user_id;
            ALTER TABLE auth_user_user_permissions DROP COLUMN user_id;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RemoveField(model_name='appuser', name='id'),
        migrations.RenameField(model_name='appuser', old_name='uuid', new_name='id'),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=False),
        ),
        migrations.RenameField(model_name='appuserinfo', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='appusergoals', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='userscheduledactivity', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='usercompletedlog', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='affiliatepromotiondiscountcode', old_name='assigned_user_uuid', new_name='assigned_user'),
        migrations.RenameField(model_name='affiliatepromotionredemption', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='member', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='friendcircleevent', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='appusercurrentemotion', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='appuserdailyemotion', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='userexercisemax', old_name='user_uuid', new_name='user'),
        migrations.RenameField(model_name='appuserfatiguemodel', old_name='user_uuid', new_name='user'),
        migrations.RunSQL(
            """
            ALTER TABLE api_appuser_max_propositions RENAME COLUMN appuser_uuid TO appuser_id;
            ALTER TABLE api_affiliatepromotion_assigned_users RENAME COLUMN appuser_uuid TO appuser_id;
            ALTER TABLE auth_user_groups RENAME COLUMN user_uuid TO user_id;
            ALTER TABLE auth_user_user_permissions RENAME COLUMN user_uuid TO user_id;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='user',
            field=models.OneToOneField(to='api.AppUser', on_delete=models.CASCADE, related_name='info', null=True),
        ),
        migrations.AlterField(
            model_name='appusergoals',
            name='user',
            field=models.OneToOneField(to='api.AppUser', on_delete=models.CASCADE, related_name='goals', null=True),
        ),
        migrations.AlterField(
            model_name='userscheduledactivity',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='scheduled_activities', null=True),
        ),
        migrations.AlterField(
            model_name='usercompletedlog',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='completion_logs', null=True),
        ),
        migrations.AlterField(
            model_name='affiliatepromotiondiscountcode',
            name='assigned_user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='discount_codes', null=True),
        ),
        migrations.AlterField(
            model_name='affiliatepromotionredemption',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='promotion_redemptions', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='circle_memberships', null=True),
        ),
        migrations.AlterField(
            model_name='friendcircleevent',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='friend_circle_events', null=True),
        ),
        migrations.AlterField(
            model_name='appusercurrentemotion',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='current_emotions', null=True),
        ),
        migrations.AlterField(
            model_name='appuserdailyemotion',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='daily_emotions', null=True),
        ),
        migrations.AlterField(
            model_name='userexercisemax',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='exercise_maxes', null=True),
        ),
        migrations.AlterField(
            model_name='appuserfatiguemodel',
            name='user',
            field=models.ForeignKey(to='api.AppUser', on_delete=models.CASCADE, related_name='muscle_fatigue', null=True),
        ),
    ]
