# Generated by Django 5.2.1 on 2025-06-12 01:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_appuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatepromotiondiscountcode',
            name='assigned_user',
            field=models.ForeignKey(help_text='The user this specific code is assigned to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affiliatepromotionredemption',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appusercurrentemotion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_emotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuserdailyemotion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_emotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuserfatiguemodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user whose muscle fatigue is being tracked.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muscle_fatigue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appusergoals',
            name='goals_general',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lose_weight', 'Lose weight'), ('build_muscle', 'Build muscle'), ('get_more_flexible', 'Get more flexible'), ('get_stronger', 'Get stronger'), ('eat_healthier', 'Eat healthier'), ('regulate_energy', 'Regulate energy'), ('sleep_better', 'Sleep better'), ('manage_stress', 'Manage stress'), ('drink_more_water', 'Drink more water')], max_length=50), blank=True, default=list, help_text="The user's chosen general wellness goals.", size=None),
        ),
        migrations.AlterField(
            model_name='appusergoals',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The AppUser associated with this goal set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appuserinfo',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The AppUser associated with this extra info.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendcircle',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the friend circle.', null=True, upload_to='friend_circle_covers/'),
        ),
        migrations.AlterField(
            model_name='friendcircleevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user associated with the event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_circle_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='isAdmin',
            field=models.BooleanField(default=False, help_text='Designates whether this member is an admin of the friend circle.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Reference to the AppUser who is a member of the friend circle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompletedlog',
            name='user',
            field=models.ForeignKey(help_text='The user who completed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userexercisemax',
            name='user',
            field=models.ForeignKey(help_text='The user for whom this 1RM is recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_maxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userscheduledactivity',
            name='user',
            field=models.ForeignKey(help_text='The user for whom this activity is scheduled.', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
