# Generated by Django 5.2.1 on 2025-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_outstandingtoken_user_id_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='', help_text="User's first name.", max_length=150),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='', help_text="User's last name.", max_length=150),
        ),
    ]
