# Generated by Django 5.2 on 2025-06-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_appuser_name_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='current_streak',
            field=models.IntegerField(default=0, help_text="User's current daily tracking streak."),
        ),
        migrations.AddField(
            model_name='appuser',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text="User's longest all-time daily tracking streak."),
        ),
        migrations.AddField(
            model_name='appuser',
            name='streak_points',
            field=models.IntegerField(default=0, help_text='Points earned from streaks.'),
        ),
    ]
