# Generated by Django 5.2.3 on 2025-06-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_weeklyplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
    ]
