# Generated by Django 5.2.3 on 2025-06-23 20:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_delete_weeklyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_equipment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bands', 'Bands'), ('barbell', 'Barbell'), ('body only', 'Body Only'), ('cable', 'Cable'), ('dumbbell', 'Dumbbell'), ('e-z curl bar', 'E-Z Curl Bar'), ('exercise ball', 'Exercise Ball'), ('foam roll', 'Foam Roll'), ('kettlebells', 'Kettlebells'), ('machine', 'Machine'), ('medicine ball', 'Medicine Ball'), ('none', 'None'), ('other', 'Other')], max_length=50), blank=True, default=list, help_text='A list of fitness equipment available to the user.', size=None)),
                ('user', models.OneToOneField(help_text='The AppUser associated with this equipment list.', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
