# Generated by Django 5.2.3 on 2025-06-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_appuserequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserinfo',
            name='include_cardio',
            field=models.BooleanField(default=True, help_text="User's preference for including cardio in their weekly plan."),
        ),
    ]
