# Generated by Django 5.2.3 on 2025-07-02 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_appuserinfo_include_cardio'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'db_table': 'website_university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaitlistedAppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(default=None, null=True, unique=True)),
                ('referrals', models.IntegerField(default=0)),
                ('referral_link', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'website_waitlistedappuser',
                'managed': False,
            },
        ),
    ]
