# Generated by Django 5.2.3 on 2025-07-15 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_university_waitlistedappuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The display name of the shortcut.', max_length=100)),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Mind', 'Mind'), ('Sleep', 'Sleep')], help_text='The category the shortcut belongs to.', max_length=50)),
                ('action_identifier', models.CharField(help_text="A unique key for the frontend to identify the shortcut's action.", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of what the shortcut does.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shortcut is available for users to select.')),
            ],
            options={
                'verbose_name': 'Dashboard Shortcut',
                'verbose_name_plural': 'Dashboard Shortcuts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserShortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text="The display order of the shortcut on the user's dashboard.")),
                ('shortcut', models.ForeignKey(help_text='The shortcut selected by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_selections', to='api.shortcut')),
                ('user', models.ForeignKey(help_text='The user who has this shortcut.', on_delete=django.db.models.deletion.CASCADE, related_name='shortcut_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Shortcut',
                'verbose_name_plural': 'User Shortcuts',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'shortcut')},
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='shortcuts',
            field=models.ManyToManyField(blank=True, help_text="User's selected dashboard shortcuts.", related_name='shortcut_users', through='api.UserShortcut', to='api.shortcut'),
        ),
    ]
