# Generated by Django 5.2.3 on 2025-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_shortcut_usershortcut_appuser_shortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='category',
            field=models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Mind', 'Mind'), ('Sleep', 'Sleep'), ('Other', 'Other')], help_text='The category the shortcut belongs to.', max_length=50),
        ),
    ]
