# Generated by Django 5.2.4 on 2025-07-17 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_shortcut_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, help_text="The type of activity displayed in the UI (e.g., 'Workout', 'Recipe', 'Meditation').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Sleep', 'Sleep'), ('Mind', 'Mind'), ('Routine', 'Routine'), ('Other', 'Other')], max_length=50), blank=True, default=list, help_text='Category or categories of the activity.', size=None),
        ),
    ]
