# Generated by Django 5.2.4 on 2025-07-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_set_default_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduledactivity',
            name='scheduled_display_time',
            field=models.CharField(blank=True, help_text="Display time for the activity (e.g., 'Morning', '9:30 AM').", max_length=50, null=True),
        ),
    ]
