# Generated by Django 5.2.4 on 2025-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_add_scheduled_display_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Workout', 'Workout'),
                    ('Weight Tracking', 'Weight Tracking'),
                    ('Personal Record', 'Personal Record'),
                    ('Food Log', 'Food Log'),
                    ('Water Intake', 'Water Intake'),
                    ('Caffeine Log', 'Caffeine Log'),
                    ('Alcohol Log', 'Alcohol Log'),
                    ('Recipe', 'Recipe'),
                    ('Supplement Log', 'Supplement Log'),
                    ('Journal', 'Journal'),
                    ('Meditation', 'Meditation'),
                    ('Breathing', 'Breathing'),
                    ('Mood Check', 'Mood Check'),
                    ('Emotions Check', 'Emotions Check'),
                    ('Energy Level Log', 'Energy Level Log'),
                    ('Sleep Tracking', 'Sleep Tracking'),
                    ('Sleep Debt Calculation', 'Sleep Debt Calculation'),
                    ('Prescription Log', 'Prescription Log'),
                    ('Sex Log', 'Sex Log'),
                    ('Symptoms Log', 'Symptoms Log'),
                    ('Cycle Log', 'Cycle Log'),
                    ('Routine', 'Routine'),
                    ('Mindfulness', 'Mindfulness'),
                    ('Other', 'Other'),
                ],
                help_text='The type of activity displayed in the UI.',
                max_length=50,
                null=True
            ),
        ),
    ] 