# Generated by Django 5.2.4 on 2025-07-18 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_add_activity_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the routine.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A description of the routine.')),
                ('scheduled_time', models.TimeField(blank=True, help_text='The time at which this routine is scheduled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this routine.', on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Routine',
                'verbose_name_plural': 'User Routines',
                'ordering': ['user', 'created_at'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the routine step.', max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., from SF Symbols) for the step.', max_length=50)),
                ('order', models.PositiveIntegerField(help_text='The order of this step within the routine.')),
                ('routine', models.ForeignKey(help_text='The routine this step belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.routine')),
            ],
            options={
                'verbose_name': 'Routine Step',
                'verbose_name_plural': 'Routine Steps',
                'ordering': ['routine', 'order'],
                'unique_together': {('routine', 'order')},
            },
        ),
    ]
