# Generated by Django 5.2.4 on 2025-07-19 21:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_routine_routinestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The title of the journal entry.', max_length=255)),
                ('content', models.TextField(help_text='The main content/body of the journal entry.')),
                ('date_created', models.DateField(default=django.utils.timezone.now, help_text='The date when this journal entry was created.')),
                ('time_created', models.TimeField(default=django.utils.timezone.now, help_text='The time when this journal entry was created.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Full timestamp when the journal entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Full timestamp when the journal entry was last updated.')),
                ('user', models.ForeignKey(help_text='The user who created this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date_created', '-time_created'],
            },
        ),
    ]
