# Generated by Django 5.2.4 on 2025-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_add_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduledactivity',
            name='generated_description',
            field=models.TextField(blank=True, help_text='System-generated description for this scheduled activity instance.', null=True),
        ),
    ]
