# Generated by Django 5.2.4 on 2025-07-21 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_add_generated_description_to_user_scheduled_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindfulnessSessionTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date when this session was completed.')),
                ('session_type', models.CharField(choices=[('meditation', 'Meditation'), ('breathing', 'Breathing Exercise'), ('mindfulness', 'Mindfulness Practice'), ('yoga', 'Yoga/Movement'), ('other', 'Other')], help_text='Type of mindfulness session.', max_length=50)),
                ('session_name', models.CharField(blank=True, help_text='Name or description of the session.', max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the session in minutes.')),
                ('mood_before', models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('neutral', 'Neutral'), ('good', 'Good'), ('excellent', 'Excellent')], help_text='Mood/stress level before the session.', max_length=20, null=True)),
                ('mood_after', models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('neutral', 'Neutral'), ('good', 'Good'), ('excellent', 'Excellent')], help_text='Mood/stress level after the session.', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the session.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who completed this mindfulness session.', on_delete=django.db.models.deletion.CASCADE, related_name='mindfulness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mindfulness Session',
                'verbose_name_plural': 'Mindfulness Sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMindfulnessTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date for which mindfulness is being tracked.')),
                ('total_minutes', models.PositiveIntegerField(default=0, help_text='Total mindfulness minutes for this date.')),
                ('mindfulness_goal_minutes', models.PositiveIntegerField(default=30, help_text='Daily mindfulness goal in minutes.')),
                ('session_count', models.PositiveIntegerField(default=0, help_text='Number of mindfulness sessions completed.')),
                ('meditation_sessions', models.PositiveIntegerField(default=0, help_text='Number of meditation sessions.')),
                ('breathing_sessions', models.PositiveIntegerField(default=0, help_text='Number of breathing exercise sessions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user whose daily mindfulness is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_mindfulness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Mindfulness Tracker',
                'verbose_name_plural': 'Daily Mindfulness Trackers',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SleepSessionTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleep_date', models.DateField(help_text='The date when this sleep session ended (wake-up date).')),
                ('bedtime', models.DateTimeField(help_text='When the user went to bed.')),
                ('wake_time', models.DateTimeField(help_text='When the user woke up.')),
                ('total_sleep_hours', models.FloatField(help_text='Total hours of sleep.')),
                ('sleep_goal_hours', models.FloatField(default=8.0, help_text="User's sleep goal in hours.")),
                ('rem_sleep_hours', models.FloatField(default=0.0, help_text='Hours spent in REM sleep.')),
                ('deep_sleep_hours', models.FloatField(default=0.0, help_text='Hours spent in deep sleep.')),
                ('light_sleep_hours', models.FloatField(default=0.0, help_text='Hours spent in light sleep.')),
                ('sleep_efficiency_percentage', models.FloatField(default=0.0, help_text='Sleep efficiency as a percentage (time asleep / time in bed).')),
                ('sleep_score', models.PositiveIntegerField(default=0, help_text='Overall sleep score (0-100).')),
                ('times_awakened', models.PositiveIntegerField(default=0, help_text='Number of times the user woke up during the night.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about sleep quality or factors.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user whose sleep is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sleep Session',
                'verbose_name_plural': 'Sleep Sessions',
                'ordering': ['-sleep_date'],
                'unique_together': {('user', 'sleep_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyMindfulnessTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(help_text='The Monday that starts this week.')),
                ('total_meditations', models.PositiveIntegerField(default=0, help_text='Total meditation sessions this week.')),
                ('meditation_goal', models.PositiveIntegerField(default=7, help_text='Weekly meditation session goal.')),
                ('total_breathing_exercises', models.PositiveIntegerField(default=0, help_text='Total breathing exercise sessions this week.')),
                ('breathing_goal', models.PositiveIntegerField(default=10, help_text='Weekly breathing exercise session goal.')),
                ('total_journal_entries', models.PositiveIntegerField(default=0, help_text='Total journal entries this week.')),
                ('journal_goal', models.PositiveIntegerField(default=5, help_text='Weekly journal entry goal.')),
                ('total_mindfulness_minutes', models.PositiveIntegerField(default=0, help_text='Total mindfulness minutes this week.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user whose weekly mindfulness is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_mindfulness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Mindfulness Tracker',
                'verbose_name_plural': 'Weekly Mindfulness Trackers',
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySleepTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(help_text='The Monday that starts this week.')),
                ('average_sleep_hours', models.FloatField(default=0.0, help_text='Average hours of sleep for this week.')),
                ('sleep_goal_hours', models.FloatField(default=8.0, help_text='Weekly sleep goal in hours per night.')),
                ('consistency_score', models.PositiveIntegerField(default=0, help_text='Sleep consistency score (0-100) based on regularity.')),
                ('average_sleep_score', models.PositiveIntegerField(default=0, help_text='Average sleep score for the week.')),
                ('nights_tracked', models.PositiveIntegerField(default=0, help_text='Number of nights with sleep data this week.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user whose weekly sleep is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_sleep', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Sleep Tracker',
                'verbose_name_plural': 'Weekly Sleep Trackers',
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
