# Generated by Django 5.2.4 on 2025-07-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_mindfulnesssessiontracker_dailymindfulnesstracker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindfulnesssessiontracker',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='sleepsessiontracker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sleepsessiontracker',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weeklymindfulnesstracker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklymindfulnesstracker',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weeklysleeptracker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklysleeptracker',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyMindfulnessTracker',
        ),
        migrations.DeleteModel(
            name='MindfulnessSessionTracker',
        ),
        migrations.DeleteModel(
            name='SleepSessionTracker',
        ),
        migrations.DeleteModel(
            name='WeeklyMindfulnessTracker',
        ),
        migrations.DeleteModel(
            name='WeeklySleepTracker',
        ),
    ]
