# Generated by Django 5.2.4 on 2025-07-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_mindfulnesssessiontracker_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxproposition',
            name='associated_affiliate_promotion',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='max_propositions',
        ),
        migrations.DeleteModel(
            name='AffiliatePromotionDiscountCode',
        ),
        migrations.DeleteModel(
            name='MaxProposition',
        ),
    ]
