# Generated by Django 5.2.4 on 2025-07-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_change_lifetime_savings_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='lifetime_savings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total savings earned by the user over their lifetime in dollars (e.g., 115.30).', max_digits=6),
        ),
    ]
