# Generated by Django 5.2.4 on 2025-07-28 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_appuser_lifetime_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Name of the product/service (denormalized from promotion title).', max_length=255)),
                ('product_description', models.TextField(blank=True, help_text='Description of the product/service (denormalized from promotion).')),
                ('product_image', models.ImageField(blank=True, help_text='Image of the product (copied from promotion or custom uploaded).', null=True, upload_to='user_product_images/')),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Nutrition', 'Nutrition'), ('Health', 'Health'), ('Wellness', 'Wellness'), ('Beauty', 'Beauty'), ('Supplements', 'Supplements'), ('Food', 'Food'), ('Other', 'Other')], default='Other', help_text='Category of the product for organization in UI.', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', help_text="Current status of the user's product.", max_length=20)),
                ('redeemed_at', models.DateTimeField(help_text='When the user redeemed this product (copied from redemption).')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this product expires (if applicable).', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the user last interacted with this product.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate_name', models.CharField(help_text='Name of the affiliate (denormalized for display).', max_length=255)),
                ('points_spent', models.IntegerField(default=0, help_text='Points spent to redeem this product.')),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, help_text='Original monetary value of the product.', max_digits=10, null=True)),
                ('user_notes', models.TextField(blank=True, help_text='Personal notes the user can add about this product.')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether the user has marked this as a favorite product.')),
                ('source_promotion', models.ForeignKey(blank=True, help_text='The original promotion that was redeemed (nullable for data integrity).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_products', to='api.affiliatepromotion')),
                ('source_redemption', models.OneToOneField(blank=True, help_text='The redemption record that created this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_product', to='api.affiliatepromotionredemption')),
                ('user', models.ForeignKey(help_text='The user who owns this product.', on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Product',
                'verbose_name_plural': 'User Products',
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_userpro_user_id_45d20e_idx'), models.Index(fields=['user', 'category'], name='api_userpro_user_id_476d4b_idx'), models.Index(fields=['user', 'redeemed_at'], name='api_userpro_user_id_a4f166_idx')],
            },
        ),
    ]
