# Generated by Django 5.2.4 on 2025-07-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_create_user_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendcircle',
            name='cover_image',
            field=models.CharField(blank=True, help_text="Cover image asset name for the friend circle (e.g., 'friendcircleimage0').", max_length=100, null=True),
        ),
    ]
