# Generated by Django 5.2.4 on 2025-07-29 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_change_friendcircle_cover_image_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCircleInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_phone', models.CharField(help_text='Phone number of the person being invited (format: +11234567890).', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current status of the invitation.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was created.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted or declined.', null=True)),
                ('friend_circle', models.ForeignKey(help_text='The friend circle for which the invitation is sent.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.friendcircle')),
                ('invitee_user', models.ForeignKey(blank=True, help_text='The AppUser if they have an account (populated when invitation is sent).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='The user who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend Circle Invitation',
                'verbose_name_plural': 'Friend Circle Invitations',
                'ordering': ['-created_at'],
                'unique_together': {('friend_circle', 'invitee_phone')},
            },
        ),
    ]
