# Generated by Django 5.2.4 on 2025-07-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_add_friend_circle_invitation'),
    ]

    operations = [
        # Rename models
        migrations.RenameModel(
            old_name='FriendCircle',
            new_name='FriendGroup',
        ),
        migrations.RenameModel(
            old_name='FriendCircleEvent',
            new_name='FriendGroupEvent',
        ),
        migrations.RenameModel(
            old_name='FriendCircleInvitation',
            new_name='FriendGroupInvitation',
        ),
        
        # Rename foreign key fields in Member model
        migrations.RenameField(
            model_name='member',
            old_name='friend_circle',
            new_name='friend_group',
        ),
        
        # Rename foreign key fields in FriendGroupEvent model
        migrations.RenameField(
            model_name='friendgroupevent',
            old_name='friend_circle',
            new_name='friend_group',
        ),
        
        # Rename foreign key fields in FriendGroupInvitation model
        migrations.RenameField(
            model_name='friendgroupinvitation',
            old_name='friend_circle',
            new_name='friend_group',
        ),
    ]
