# Generated by Django 5.1.6 on 2025-05-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(blank=True, help_text='Grams of carbohydrates.', null=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='fat',
            field=models.FloatField(blank=True, help_text='Grams of fat.', null=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_name',
            field=models.CharField(blank=True, help_text='Name of the food consumed (auto‐populated from product).', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(blank=True, help_text='Grams of protein.', null=True),
        ),
    ]
