# Generated by Django 5.2.1 on 2025-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='nutriscore_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='nutriscore_grade_producer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='nutrition_grades',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
