# Generated by Django 5.2.1 on 2025-06-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_foodproduct_nutriscore_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients_value',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_fruits_vegetables_legumes_from_category',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_fruits_vegetables_nuts_estimate',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_fruits_vegetables_nuts_from_category_value',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrition_score_warning_nutriments_estimated',
        ),
    ]
