# Generated by Django 5.2 on 2025-06-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_foodentry_carbs_alter_foodentry_fat_and_more'),
        ('nutrition', '0003_remove_foodproduct_nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients_and_m'),
    ]

    operations = [
    ]
