# Generated by Django 5.2 on 2025-06-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_dailycalorietracker_user_id_to_uuid'),
        ('nutrition', '0004_merge_20250614_0043'),
    ]

    operations = [
    ]
