# Generated by Django 5.2 on 2025-06-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_merge_20250614_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycalorietracker',
            name='calcium_milligrams',
            field=models.FloatField(default=0.0, help_text='Milligrams of calcium.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='fiber_grams',
            field=models.FloatField(default=0.0, help_text='Grams of fiber.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='folate_micrograms',
            field=models.FloatField(default=0.0, help_text='Micrograms of Folate (B9).'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='iron_milligrams',
            field=models.FloatField(default=0.0, help_text='Milligrams of iron.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='potassium_milligrams',
            field=models.FloatField(default=0.0, help_text='Milligrams of Potassium.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='vitamin_a_micrograms',
            field=models.FloatField(default=0.0, help_text='Micrograms of Vitamin A (RAE).'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='vitamin_b12_micrograms',
            field=models.FloatField(default=0.0, help_text='Micrograms of Vitamin B12.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='vitamin_c_milligrams',
            field=models.FloatField(default=0.0, help_text='Milligrams of Vitamin C.'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='calcium_milligrams',
            field=models.FloatField(blank=True, help_text='Milligrams of calcium.', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fiber_grams',
            field=models.FloatField(blank=True, help_text='Grams of fiber.', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='folate_micrograms',
            field=models.FloatField(blank=True, help_text='Micrograms of Folate (B9).', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='iron_milligrams',
            field=models.FloatField(blank=True, help_text='Milligrams of iron.', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='potassium_milligrams',
            field=models.FloatField(blank=True, help_text='Milligrams of Potassium.', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='vitamin_a_micrograms',
            field=models.FloatField(blank=True, help_text='Micrograms of Vitamin A (RAE).', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='vitamin_b12_micrograms',
            field=models.FloatField(blank=True, help_text='Micrograms of Vitamin B12.', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='vitamin_c_milligrams',
            field=models.FloatField(blank=True, help_text='Milligrams of Vitamin C.', null=True),
        ),
    ]
