# Generated by Django 5.2.3 on 2025-06-19 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_customfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='custom_food',
            field=models.ForeignKey(blank=True, help_text='The custom food consumed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='nutrition.customfood'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_product',
            field=models.ForeignKey(blank=True, help_text='The food product consumed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='nutrition.foodproduct'),
        ),
    ]
