# Generated by Django 5.2 on 2025-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_foodentry_custom_food_alter_foodentry_food_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('food_product__isnull', False), ('custom_food__isnull', True)), models.Q(('food_product__isnull', True), ('custom_food__isnull', False)), _connector='OR'), name='only_one_of_food_product_or_custom_food'),
        ),
    ]
