# Generated by Django 5.2.3 on 2025-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_foodentry_custom_food_alter_foodentry_food_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='popularity_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
