# Generated by Django 5.2.3 on 2025-06-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_foodproduct_popularity_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='popularity_key',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(condition=models.Q(('popularity_key__gt', 0)), fields=['popularity_key'], name='popularity_key_partial_idx'),
        ),
    ]
