# Generated by Django 5.2 on 2025-06-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_foodentry_only_one_of_food_product_or_custom_food'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='foodentry',
            name='only_one_of_food_product_or_custom_food',
        ),
    ]
