# Generated by Django 5.2 on 2025-06-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_remove_foodentry_only_one_of_food_product_or_custom_food'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='barcode_id',
            field=models.CharField(blank=True, help_text='Optional barcode for this custom food.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
