# Generated by Django 5.2 on 2025-06-22 21:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_remove_foodentry_only_one_of_food_product_or_custom_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='barcode_id',
            field=models.CharField(blank=True, help_text='Optional barcode for this custom food.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
