# Generated by Django 5.2 on 2025-06-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_alter_customfood_barcode_id_alter_customfood_id'),
        ('nutrition', '0011_alter_customfood_barcode_id_and_more'),
    ]

    operations = [
    ]
