# Generated by Django 5.2.3 on 2025-06-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_alter_foodproduct_popularity_key_and_more'),
        ('nutrition', '0012_merge_20250622_2115'),
    ]

    operations = [
    ]
