# Generated by Django 5.2.3 on 2025-06-23 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_merge_20250623_2002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='barcode_id',
            field=models.CharField(blank=True, help_text='Optional unique barcode ID for this food.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='calories',
            field=models.FloatField(help_text='Calories per serving.'),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='name',
            field=models.CharField(help_text='The name of the custom food.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='user',
            field=models.ForeignKey(help_text='The user who created this custom food.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
