# Generated by Django 5.2.3 on 2025-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
