# Generated by Django 5.2 on 2025-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_alter_customfood_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['product_name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['brands'], name='brands_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['nutriscore_grade'], name='nutriscore_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['nova_group'], name='nova_group_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['obsolete'], name='obsolete_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['brand_owner'], name='brand_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['product_name', 'brands'], name='product_brand_combined_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['product_name_en'], name='product_name_en_idx'),
        ),
    ]
