# Generated by Django 5.2 on 2025-07-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0020_improve_search_vector_weighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycalorietracker',
            name='alcohol_grams',
            field=models.FloatField(default=0.0, help_text='Total grams of alcohol consumed for the day.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='standard_drinks',
            field=models.FloatField(default=0.0, help_text='Total standard drinks consumed for the day.'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='alcohol_category',
            field=models.CharField(blank=True, help_text='Category of the alcoholic beverage.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='alcohol_grams',
            field=models.FloatField(blank=True, help_text='Grams of alcohol in this entry.', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='standard_drinks',
            field=models.FloatField(blank=True, help_text='Number of standard drinks in this entry.', null=True),
        ),
        migrations.CreateModel(
            name='AlcoholicBeverage',
            fields=[
                ('_id', models.CharField(help_text='Unique identifier for the beverage', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the alcoholic beverage', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Brand name', max_length=255, null=True)),
                ('category', models.CharField(choices=[('beer', 'Beer (bottle/can or pint)'), ('wine', 'Glass of wine'), ('champagne', 'Champagne / sparkling wine (flute)'), ('fortified_wine', 'Fortified wine / dessert wine (small glass)'), ('liquor', 'Shot of liquor (straight spirit)'), ('cocktail', 'Mixed drink / Cocktail')], help_text='Beverage category', max_length=20)),
                ('alcohol_content_percent', models.FloatField(help_text='Alcohol content by volume percentage')),
                ('alcohol_grams', models.FloatField(default=14.0, help_text='Grams of pure alcohol (always 14g for standard drink)')),
                ('calories', models.FloatField(help_text='Calories per standard drink')),
                ('carbs_grams', models.FloatField(help_text='Grams of carbohydrates per standard drink')),
                ('serving_size_ml', models.FloatField(help_text='Serving size in milliliters')),
                ('serving_description', models.CharField(help_text='Human-readable serving description', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('popularity_score', models.IntegerField(default=50, help_text='Popularity score (1-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nutrition_alcoholic_beverage',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['category'], name='nutrition_a_categor_f9641f_idx'), models.Index(fields=['popularity_score'], name='nutrition_a_popular_b5f55a_idx'), models.Index(fields=['name'], name='nutrition_a_name_4f09f9_idx')],
            },
        ),
        migrations.AddField(
            model_name='foodentry',
            name='alcoholic_beverage',
            field=models.ForeignKey(blank=True, help_text='The alcoholic beverage consumed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='nutrition.alcoholicbeverage'),
        ),
    ]
