# Generated by Django 5.2 on 2025-07-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0022_add_alcohol_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineProduct',
            fields=[
                ('_id', models.CharField(help_text='Unique identifier for the product', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the caffeine product', max_length=255)),
                ('brand', models.CharField(blank=True, help_text='Brand name', max_length=255, null=True)),
                ('category', models.CharField(choices=[('energy_drink', 'Energy Drink'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('soda', 'Soda/Soft Drink'), ('supplement', 'Supplement'), ('other', 'Other')], help_text='Product category', max_length=20)),
                ('sub_category', models.CharField(blank=True, help_text='Sub-category of the product', max_length=50, null=True)),
                ('flavor_or_variant', models.CharField(blank=True, help_text='Flavor or variant of the product', max_length=255, null=True)),
                ('serving_size_ml', models.FloatField(help_text='Serving size in milliliters')),
                ('serving_size_desc', models.CharField(help_text='Human-readable serving description', max_length=255)),
                ('caffeine_mg_per_serving', models.FloatField(help_text='Milligrams of caffeine per serving')),
                ('caffeine_mg_per_100ml', models.FloatField(help_text='Milligrams of caffeine per 100ml')),
                ('calories_per_serving', models.FloatField(help_text='Calories per serving')),
                ('sugar_g_per_serving', models.FloatField(blank=True, help_text='Grams of sugar per serving', null=True)),
                ('upc', models.CharField(blank=True, help_text='Universal Product Code', max_length=50, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the data', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nutrition_caffeineproduct',
                'ordering': ['-caffeine_mg_per_serving', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='caffeine_mg',
            field=models.FloatField(default=0.0, help_text='Total milligrams of caffeine consumed for the day.'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='caffeine_category',
            field=models.CharField(blank=True, help_text='Category of the caffeine product.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='caffeine_mg',
            field=models.FloatField(blank=True, help_text='Milligrams of caffeine in this entry.', null=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('alcohol', 'Alcohol'), ('caffeine', 'Caffeine')], default='snack', help_text='The meal this food was consumed with.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='caffeineproduct',
            index=models.Index(fields=['category'], name='nutrition_c_categor_afb3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='caffeineproduct',
            index=models.Index(fields=['brand'], name='nutrition_c_brand_460cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='caffeineproduct',
            index=models.Index(fields=['caffeine_mg_per_serving'], name='nutrition_c_caffein_c908ef_idx'),
        ),
        migrations.AddIndex(
            model_name='caffeineproduct',
            index=models.Index(fields=['name'], name='nutrition_c_name_15a85c_idx'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='caffeine_product',
            field=models.ForeignKey(blank=True, help_text='The caffeine product consumed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='nutrition.caffeineproduct'),
        ),
    ]
