# Generated by Django 5.2 on 2025-07-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0023_add_caffeine_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffeineproduct',
            name='caffeine_mg_per_100ml',
            field=models.FloatField(blank=True, null=True, help_text='Milligrams of caffeine per 100ml'),
        ),
    ] 