# Generated by Django 5.2 on 2025-07-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0024_make_caffeine_per_100ml_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.FloatField(help_text='Amount of water consumed in milliliters.')),
                ('container_type', models.CharField(choices=[('glass', 'Glass (250ml)'), ('cup', 'Cup (240ml)'), ('bottle_small', 'Small Bottle (330ml)'), ('bottle_large', 'Large Bottle (500ml)'), ('bottle_xl', 'XL Bottle (1000ml)'), ('custom', 'Custom Amount')], default='glass', help_text='Type of container used for drinking.', max_length=20)),
                ('time_consumed', models.DateTimeField(help_text='When the water was consumed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_consumed'],
            },
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='water_goal_ml',
            field=models.FloatField(default=2000.0, help_text='Daily water intake goal in milliliters.'),
        ),
        migrations.AddField(
            model_name='dailycalorietracker',
            name='water_ml',
            field=models.FloatField(default=0.0, help_text='Total milliliters of water consumed for the day.'),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='daily_log',
            field=models.ForeignKey(help_text='The daily log this water entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='water_entries', to='nutrition.dailycalorietracker'),
        ),
    ]
