# Generated by Django 5.2 on 2025-07-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0025_add_water_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alcoholicbeverage',
            new_name='nutrition_a_categor_223124_idx',
            old_name='nutrition_a_categor_f9641f_idx',
        ),
        migrations.RenameIndex(
            model_name='alcoholicbeverage',
            new_name='nutrition_a_popular_36e818_idx',
            old_name='nutrition_a_popular_b5f55a_idx',
        ),
        migrations.RenameIndex(
            model_name='alcoholicbeverage',
            new_name='nutrition_a_name_529950_idx',
            old_name='nutrition_a_name_4f09f9_idx',
        ),
        migrations.AlterModelTable(
            name='alcoholicbeverage',
            table='nutrition_alcoholicbeverage',
        ),
    ]
