# Generated by Django 5.1.6 on 2025-05-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='isCardio',
            field=models.BooleanField(default=False),
        ),
    ]
