# Generated by Django 5.1.6 on 2025-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_exercise_iscardio'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
