# Generated by Django 5.2.1 on 2025-05-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_workoutexercise_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='primary_cluster',
            field=models.CharField(blank=True, choices=[('Vertical Push', 'Vertical Push'), ('Horizontal Push', 'Horizontal Push'), ('Vertical Pull', 'Vertical Pull'), ('Horizontal Pull', 'Horizontal Pull'), ('Hip Hinge', 'Hip Hinge'), ('Knee Dominant', 'Knee Dominant'), ('Core Brace', 'Core Brace')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_cluster',
            field=models.CharField(blank=True, choices=[('compound', 'Compound'), ('isolation', 'Isolation')], max_length=100, null=True),
        ),
    ]
