# Generated by Django 5.2.1 on 2025-05-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_exercise_primary_cluster_exercise_secondary_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='point_value',
        ),
    ]
