# Generated by Django 5.2.1 on 2025-05-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_exercise_point_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='primary_cluster',
            new_name='cluster',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_cluster',
        ),
    ]
