# Generated by Django 5.2.1 on 2025-05-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_rename_primary_cluster_exercise_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='isDiagnostic',
            field=models.BooleanField(default=False),
        ),
    ]
