# Generated by Django 5.2.1 on 2025-05-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_exercise_isdiagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
