# Generated by Django 5.2.1 on 2025-05-16 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_alter_exercise_secondary_muscles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTransferCoefficient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coefficient', models.FloatField(help_text='The transfer coefficient value (e.g., 1RM_to = coefficient * 1RM_from).')),
                ('derivation_method', models.CharField(choices=[('USER_INPUT', 'User Input'), ('SYSTEM_CALCULATED', 'System Calculated'), ('INITIAL_SEED', 'Initial Seed')], default='INITIAL_SEED', help_text='How this transfer coefficient was determined.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or context about this coefficient.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_exercise', models.ForeignKey(help_text='The source exercise with a known 1RM.', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_coefficients_from', to='fitness.exercise')),
                ('to_exercise', models.ForeignKey(help_text='The target exercise for which the 1RM is being estimated.', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_coefficients_to', to='fitness.exercise')),
            ],
            options={
                'verbose_name': 'Exercise Transfer Coefficient',
                'verbose_name_plural': 'Exercise Transfer Coefficients',
                'ordering': ['from_exercise', 'to_exercise'],
                'unique_together': {('from_exercise', 'to_exercise')},
            },
        ),
    ]
