# Generated by Django 5.2.3 on 2025-06-18 18:45

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_exercisetransfercoefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioWorkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Cardio Session', max_length=200)),
                ('cardio_type', models.CharField(choices=[('walk', 'Walk'), ('run', 'Run'), ('bike', 'Bike'), ('row', 'Row'), ('swim', 'Swim'), ('other', 'Other')], max_length=20)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Planned duration (00:00:00). Optional for ad-hoc sessions.')),
                ('intensity', models.CharField(blank=True, help_text="Optional free-text intensity description (e.g. 'Zone 2').", max_length=50)),
                ('is_treadmill', models.BooleanField(default=False)),
                ('is_outdoor', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
