# Generated by Django 5.2.4 on 2025-07-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_exercisesessiontracker_dailyexercisetracker_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailystepstracker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailystepstracker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercisesessiontracker',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='weeklymilestracker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklymilestracker',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyExerciseTracker',
        ),
        migrations.DeleteModel(
            name='DailyStepsTracker',
        ),
        migrations.DeleteModel(
            name='ExerciseSessionTracker',
        ),
        migrations.DeleteModel(
            name='WeeklyMilesTracker',
        ),
    ]
