# Generated by Django 5.1.6 on 2025-05-08 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistedAppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(default=0)),
                ('referrals', models.IntegerField(default=0)),
                ('referral_link', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('temp_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
