# Generated by Django 5.1.6 on 2025-05-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_waitlistedappuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistedappuser',
            name='position',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
