# Generated by Django 5.1.6 on 2025-05-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistedappuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlisted_users', to='website.university'),
        ),
    ]
