# Generated by Django 5.1.6 on 2025-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_waitlistedappuser_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistedappuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='waitlistedappuser',
            name='temp_name',
        ),
        migrations.AddField(
            model_name='waitlistedappuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
