# Generated by Django 5.1.6 on 2025-05-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_name_waitlistedappuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
    ]
