# Generated by Django 5.1.6 on 2025-05-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_university_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistedappuser',
            name='email',
        ),
    ]
